name: Monitor de Proventos (BRAPI)

on:
  schedule:
    # 09:00 UTC corresponde às 06:00 no horário de Brasília
    # Executa todos os dias (domingo a sábado)
    - cron: '0 9 * * *'
  workflow_dispatch: # Mantém a opção de você rodar manualmente pelo site do GitHub quando quiser

jobs:
  monitorar-proventos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar Dependências
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests fpdf

      - name: Executar Monitoramento (BRAPI)
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
          NTFY_TOKEN: ${{ secrets.NTFY_TOKEN }}
          BRAPI_TOKEN: ${{ secrets.BRAPI_TOKEN }}
        run: python app.py
        
