workflow_dispatch
on:
  schedule:
    - cron: '0 11 * * *' # Executa diariamente às 08:00 AM (Horário de Brasília)
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python app.py
      
